// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pooling2d_large_cl_nopad_pad_me.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pooling2d_large_cl_nopad_pad_me::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pooling2d_large_cl_nopad_pad_me::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state1 = "1";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state2 = "10";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state3 = "100";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state4 = "1000";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state5 = "10000";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state6 = "100000";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> pooling2d_large_cl_nopad_pad_me::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_2 = "10";
const sc_lv<1> pooling2d_large_cl_nopad_pad_me::ap_const_lv1_0 = "0";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_8 = "1000";
const sc_lv<1> pooling2d_large_cl_nopad_pad_me::ap_const_lv1_1 = "1";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_1 = "1";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_3 = "11";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_4 = "100";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_5 = "101";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_7 = "111";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_9 = "1001";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_A = "1010";
const sc_lv<8> pooling2d_large_cl_nopad_pad_me::ap_const_lv8_0 = "00000000";
const sc_lv<7> pooling2d_large_cl_nopad_pad_me::ap_const_lv7_0 = "0000000";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_6 = "110";
const sc_lv<3> pooling2d_large_cl_nopad_pad_me::ap_const_lv3_0 = "000";
const sc_lv<3> pooling2d_large_cl_nopad_pad_me::ap_const_lv3_1 = "1";
const sc_lv<64> pooling2d_large_cl_nopad_pad_me::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<8> pooling2d_large_cl_nopad_pad_me::ap_const_lv8_A9 = "10101001";
const sc_lv<8> pooling2d_large_cl_nopad_pad_me::ap_const_lv8_1 = "1";
const sc_lv<7> pooling2d_large_cl_nopad_pad_me::ap_const_lv7_40 = "1000000";
const sc_lv<7> pooling2d_large_cl_nopad_pad_me::ap_const_lv7_1 = "1";
const sc_lv<32> pooling2d_large_cl_nopad_pad_me::ap_const_lv32_C = "1100";
const sc_lv<3> pooling2d_large_cl_nopad_pad_me::ap_const_lv3_4 = "100";
const sc_lv<6> pooling2d_large_cl_nopad_pad_me::ap_const_lv6_0 = "000000";
const bool pooling2d_large_cl_nopad_pad_me::ap_const_boolean_1 = true;

pooling2d_large_cl_nopad_pad_me::pooling2d_large_cl_nopad_pad_me(sc_module_name name) : sc_module(name), mVcdFile(0) {
    layer_in_V_6_U = new pooling2d_large_cl_nopad_pad_me_layer_in_V_6("layer_in_V_6_U");
    layer_in_V_6_U->clk(ap_clk);
    layer_in_V_6_U->reset(ap_rst);
    layer_in_V_6_U->address0(layer_in_V_6_address0);
    layer_in_V_6_U->ce0(layer_in_V_6_ce0);
    layer_in_V_6_U->we0(layer_in_V_6_we0);
    layer_in_V_6_U->d0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_d0);
    layer_in_V_6_U->q0(layer_in_V_6_q0);
    tmpdata_V_U = new cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config8_s_tmpinbXr("tmpdata_V_U");
    tmpdata_V_U->clk(ap_clk);
    tmpdata_V_U->reset(ap_rst);
    tmpdata_V_U->address0(tmpdata_V_address0);
    tmpdata_V_U->ce0(tmpdata_V_ce0);
    tmpdata_V_U->we0(tmpdata_V_we0);
    tmpdata_V_U->d0(data_V_V_dout);
    tmpdata_V_U->q0(tmpdata_V_q0);
    pool_V_U = new pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8b0s("pool_V_U");
    pool_V_U->clk(ap_clk);
    pool_V_U->reset(ap_rst);
    pool_V_U->address0(pool_V_address0);
    pool_V_U->ce0(pool_V_ce0);
    pool_V_U->we0(pool_V_we0);
    pool_V_U->d0(layer_in_V_6_q0);
    pool_V_U->q0(pool_V_q0);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375 = new cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s("grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375");
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->ap_clk(ap_clk);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->ap_rst(ap_rst);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->ap_start(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->ap_done(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->ap_idle(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_idle);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->ap_ready(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_ready);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->data_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_address0);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->data_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_ce0);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->data_V_q0(tmpdata_V_q0);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->output_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_address0);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->output_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_ce0);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->output_V_we0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_we0);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->output_V_d0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_d0);
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375->output_V_q0(layer_in_V_6_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln508_fu_717_p2);
    sensitive << ( zext_ln500_reg_826 );
    sensitive << ( shl_ln_fu_709_p3 );

    SC_METHOD(thread_add_ln530_fu_664_p2);
    sensitive << ( pY_1_load_reg_810 );

    SC_METHOD(thread_add_ln532_fu_675_p2);
    sensitive << ( sY_1_load_reg_800 );

    SC_METHOD(thread_add_ln535_fu_618_p2);
    sensitive << ( pX_1_load_reg_816 );

    SC_METHOD(thread_add_ln537_fu_629_p2);
    sensitive << ( sX_1_load_reg_790 );

    SC_METHOD(thread_and_ln498_3_fu_585_p2);
    sensitive << ( icmp_ln498_5_fu_563_p2 );
    sensitive << ( icmp_ln498_6_fu_573_p2 );

    SC_METHOD(thread_and_ln498_4_fu_591_p2);
    sensitive << ( and_ln498_3_fu_585_p2 );
    sensitive << ( and_ln498_fu_579_p2 );

    SC_METHOD(thread_and_ln498_fu_579_p2);
    sensitive << ( icmp_ln498_fu_543_p2 );
    sensitive << ( icmp_ln498_4_fu_553_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln489_fu_522_p2 );

    SC_METHOD(thread_ap_block_state3_ignore_call0);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln489_fu_522_p2 );

    SC_METHOD(thread_ap_block_state9);
    sensitive << ( res_V_V_full_n );
    sensitive << ( icmp_ln512_fu_732_p2 );

    SC_METHOD(thread_ap_condition_1059);
    sensitive << ( and_ln498_4_reg_822 );
    sensitive << ( icmp_ln522_fu_613_p2 );
    sensitive << ( icmp_ln500_fu_601_p2 );

    SC_METHOD(thread_ap_condition_1061);
    sensitive << ( and_ln498_4_reg_822 );
    sensitive << ( icmp_ln522_fu_613_p2 );
    sensitive << ( icmp_ln500_fu_601_p2 );

    SC_METHOD(thread_ap_condition_161);
    sensitive << ( and_ln498_4_reg_822 );
    sensitive << ( icmp_ln522_fu_613_p2 );
    sensitive << ( icmp_ln500_fu_601_p2 );
    sensitive << ( icmp_ln526_fu_659_p2 );

    SC_METHOD(thread_ap_condition_272);
    sensitive << ( and_ln498_4_reg_822 );
    sensitive << ( icmp_ln522_fu_613_p2 );
    sensitive << ( icmp_ln500_fu_601_p2 );
    sensitive << ( icmp_ln526_fu_659_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln484_fu_510_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_data_V_V_blk_n);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln489_fu_522_p2 );

    SC_METHOD(thread_data_V_V_read);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln489_fu_522_p2 );

    SC_METHOD(thread_grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start);
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start_reg );

    SC_METHOD(thread_i0_fu_528_p2);
    sensitive << ( i0_0_reg_308 );

    SC_METHOD(thread_i1_fu_607_p2);
    sensitive << ( i1_0_reg_319 );

    SC_METHOD(thread_i2_fu_699_p2);
    sensitive << ( i2_0_reg_330 );

    SC_METHOD(thread_i_fu_743_p2);
    sensitive << ( i_0_reg_353 );

    SC_METHOD(thread_i_ih_fu_516_p2);
    sensitive << ( i_ih_0_reg_297 );

    SC_METHOD(thread_icmp_ln1494_fu_749_p2);
    sensitive << ( pool_V_q0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_V_reg_342 );

    SC_METHOD(thread_icmp_ln484_fu_510_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_ih_0_reg_297 );

    SC_METHOD(thread_icmp_ln489_fu_522_p2);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln489_fu_522_p2 );
    sensitive << ( i0_0_reg_308 );

    SC_METHOD(thread_icmp_ln498_4_fu_553_p2);
    sensitive << ( sY_1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done );

    SC_METHOD(thread_icmp_ln498_5_fu_563_p2);
    sensitive << ( pY_1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done );

    SC_METHOD(thread_icmp_ln498_6_fu_573_p2);
    sensitive << ( pX_1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done );

    SC_METHOD(thread_icmp_ln498_fu_543_p2);
    sensitive << ( sX_1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done );

    SC_METHOD(thread_icmp_ln500_fu_601_p2);
    sensitive << ( and_ln498_4_reg_822 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_0_reg_319 );

    SC_METHOD(thread_icmp_ln506_fu_693_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i2_0_reg_330 );

    SC_METHOD(thread_icmp_ln512_fu_732_p2);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln512_fu_732_p2 );
    sensitive << ( i_0_reg_353 );

    SC_METHOD(thread_icmp_ln522_fu_613_p2);
    sensitive << ( pX_1_load_reg_816 );
    sensitive << ( and_ln498_4_reg_822 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln500_fu_601_p2 );

    SC_METHOD(thread_icmp_ln526_fu_659_p2);
    sensitive << ( pY_1_load_reg_810 );
    sensitive << ( and_ln498_4_reg_822 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln522_fu_613_p2 );
    sensitive << ( icmp_ln500_fu_601_p2 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln484_fu_510_p2 );

    SC_METHOD(thread_layer_in_V_6_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_address0 );
    sensitive << ( zext_ln508_2_fu_722_p1 );

    SC_METHOD(thread_layer_in_V_6_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_ce0 );

    SC_METHOD(thread_layer_in_V_6_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_we0 );

    SC_METHOD(thread_pool_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln508_fu_727_p1 );
    sensitive << ( zext_ln513_fu_738_p1 );

    SC_METHOD(thread_pool_V_ce0);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln512_fu_732_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_pool_V_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_pool_res_V_2_fu_755_p3);
    sensitive << ( pool_V_q0 );
    sensitive << ( tmp_V_reg_342 );
    sensitive << ( icmp_ln1494_fu_749_p2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_V_V_blk_n);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln512_fu_732_p2 );

    SC_METHOD(thread_res_V_V_din);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln512_fu_732_p2 );
    sensitive << ( tmp_V_reg_342 );

    SC_METHOD(thread_res_V_V_write);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln512_fu_732_p2 );

    SC_METHOD(thread_select_ln532_fu_680_p3);
    sensitive << ( icmp_ln498_4_reg_805 );
    sensitive << ( add_ln532_fu_675_p2 );

    SC_METHOD(thread_select_ln537_fu_634_p3);
    sensitive << ( icmp_ln498_reg_795 );
    sensitive << ( add_ln537_fu_629_p2 );

    SC_METHOD(thread_shl_ln_fu_709_p3);
    sensitive << ( trunc_ln508_fu_705_p1 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmpdata_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln489_fu_522_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_address0 );
    sensitive << ( zext_ln492_fu_534_p1 );

    SC_METHOD(thread_tmpdata_V_ce0);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln489_fu_522_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_ce0 );

    SC_METHOD(thread_tmpdata_V_we0);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln489_fu_522_p2 );

    SC_METHOD(thread_trunc_ln508_fu_705_p1);
    sensitive << ( i2_0_reg_330 );

    SC_METHOD(thread_zext_ln492_fu_534_p1);
    sensitive << ( i0_0_reg_308 );

    SC_METHOD(thread_zext_ln500_fu_597_p1);
    sensitive << ( i1_0_reg_319 );

    SC_METHOD(thread_zext_ln508_2_fu_722_p1);
    sensitive << ( add_ln508_fu_717_p2 );

    SC_METHOD(thread_zext_ln508_fu_727_p1);
    sensitive << ( i2_0_reg_330 );

    SC_METHOD(thread_zext_ln513_fu_738_p1);
    sensitive << ( i_0_reg_353 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_V_empty_n );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln489_fu_522_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln512_fu_732_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done );
    sensitive << ( and_ln498_4_reg_822 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln500_fu_601_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln506_fu_693_p2 );
    sensitive << ( icmp_ln484_fu_510_p2 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000000001";
    sX_1 = "00000000000000000000000000000000";
    sY_1 = "00000000000000000000000000000000";
    pY_1 = "00000000000000000000000000000000";
    pX_1 = "00000000000000000000000000000000";
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pooling2d_large_cl_nopad_pad_me_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_V_V_dout, "(port)data_V_V_dout");
    sc_trace(mVcdFile, data_V_V_empty_n, "(port)data_V_V_empty_n");
    sc_trace(mVcdFile, data_V_V_read, "(port)data_V_V_read");
    sc_trace(mVcdFile, res_V_V_din, "(port)res_V_V_din");
    sc_trace(mVcdFile, res_V_V_full_n, "(port)res_V_V_full_n");
    sc_trace(mVcdFile, res_V_V_write, "(port)res_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, layer_in_V_6_address0, "layer_in_V_6_address0");
    sc_trace(mVcdFile, layer_in_V_6_ce0, "layer_in_V_6_ce0");
    sc_trace(mVcdFile, layer_in_V_6_we0, "layer_in_V_6_we0");
    sc_trace(mVcdFile, layer_in_V_6_q0, "layer_in_V_6_q0");
    sc_trace(mVcdFile, sX_1, "sX_1");
    sc_trace(mVcdFile, sY_1, "sY_1");
    sc_trace(mVcdFile, pY_1, "pY_1");
    sc_trace(mVcdFile, pX_1, "pX_1");
    sc_trace(mVcdFile, data_V_V_blk_n, "data_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln489_fu_522_p2, "icmp_ln489_fu_522_p2");
    sc_trace(mVcdFile, res_V_V_blk_n, "res_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, icmp_ln512_fu_732_p2, "icmp_ln512_fu_732_p2");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, i_ih_fu_516_p2, "i_ih_fu_516_p2");
    sc_trace(mVcdFile, i_ih_reg_777, "i_ih_reg_777");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i0_fu_528_p2, "i0_fu_528_p2");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, sX_1_load_reg_790, "sX_1_load_reg_790");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_ready, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_ready");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done");
    sc_trace(mVcdFile, icmp_ln498_fu_543_p2, "icmp_ln498_fu_543_p2");
    sc_trace(mVcdFile, icmp_ln498_reg_795, "icmp_ln498_reg_795");
    sc_trace(mVcdFile, sY_1_load_reg_800, "sY_1_load_reg_800");
    sc_trace(mVcdFile, icmp_ln498_4_fu_553_p2, "icmp_ln498_4_fu_553_p2");
    sc_trace(mVcdFile, icmp_ln498_4_reg_805, "icmp_ln498_4_reg_805");
    sc_trace(mVcdFile, pY_1_load_reg_810, "pY_1_load_reg_810");
    sc_trace(mVcdFile, pX_1_load_reg_816, "pX_1_load_reg_816");
    sc_trace(mVcdFile, and_ln498_4_fu_591_p2, "and_ln498_4_fu_591_p2");
    sc_trace(mVcdFile, and_ln498_4_reg_822, "and_ln498_4_reg_822");
    sc_trace(mVcdFile, zext_ln500_fu_597_p1, "zext_ln500_fu_597_p1");
    sc_trace(mVcdFile, zext_ln500_reg_826, "zext_ln500_reg_826");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i1_fu_607_p2, "i1_fu_607_p2");
    sc_trace(mVcdFile, i1_reg_834, "i1_reg_834");
    sc_trace(mVcdFile, icmp_ln522_fu_613_p2, "icmp_ln522_fu_613_p2");
    sc_trace(mVcdFile, icmp_ln522_reg_839, "icmp_ln522_reg_839");
    sc_trace(mVcdFile, icmp_ln500_fu_601_p2, "icmp_ln500_fu_601_p2");
    sc_trace(mVcdFile, select_ln532_fu_680_p3, "select_ln532_fu_680_p3");
    sc_trace(mVcdFile, icmp_ln526_fu_659_p2, "icmp_ln526_fu_659_p2");
    sc_trace(mVcdFile, i2_fu_699_p2, "i2_fu_699_p2");
    sc_trace(mVcdFile, i2_reg_854, "i2_reg_854");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln506_fu_693_p2, "icmp_ln506_fu_693_p2");
    sc_trace(mVcdFile, pool_V_q0, "pool_V_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_block_state9, "ap_block_state9");
    sc_trace(mVcdFile, i_fu_743_p2, "i_fu_743_p2");
    sc_trace(mVcdFile, i_reg_877, "i_reg_877");
    sc_trace(mVcdFile, pool_res_V_2_fu_755_p3, "pool_res_V_2_fu_755_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmpdata_V_address0, "tmpdata_V_address0");
    sc_trace(mVcdFile, tmpdata_V_ce0, "tmpdata_V_ce0");
    sc_trace(mVcdFile, tmpdata_V_we0, "tmpdata_V_we0");
    sc_trace(mVcdFile, tmpdata_V_q0, "tmpdata_V_q0");
    sc_trace(mVcdFile, pool_V_address0, "pool_V_address0");
    sc_trace(mVcdFile, pool_V_ce0, "pool_V_ce0");
    sc_trace(mVcdFile, pool_V_we0, "pool_V_we0");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_idle, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_idle");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_address0, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_address0");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_ce0, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_ce0");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_address0, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_address0");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_ce0, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_ce0");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_we0, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_we0");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_d0, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_d0");
    sc_trace(mVcdFile, i_ih_0_reg_297, "i_ih_0_reg_297");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, i0_0_reg_308, "i0_0_reg_308");
    sc_trace(mVcdFile, icmp_ln484_fu_510_p2, "icmp_ln484_fu_510_p2");
    sc_trace(mVcdFile, i1_0_reg_319, "i1_0_reg_319");
    sc_trace(mVcdFile, i2_0_reg_330, "i2_0_reg_330");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_V_reg_342, "tmp_V_reg_342");
    sc_trace(mVcdFile, i_0_reg_353, "i_0_reg_353");
    sc_trace(mVcdFile, storemerge_reg_364, "storemerge_reg_364");
    sc_trace(mVcdFile, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start_reg, "grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start_reg");
    sc_trace(mVcdFile, ap_block_state3_ignore_call0, "ap_block_state3_ignore_call0");
    sc_trace(mVcdFile, zext_ln492_fu_534_p1, "zext_ln492_fu_534_p1");
    sc_trace(mVcdFile, zext_ln508_2_fu_722_p1, "zext_ln508_2_fu_722_p1");
    sc_trace(mVcdFile, zext_ln508_fu_727_p1, "zext_ln508_fu_727_p1");
    sc_trace(mVcdFile, zext_ln513_fu_738_p1, "zext_ln513_fu_738_p1");
    sc_trace(mVcdFile, select_ln537_fu_634_p3, "select_ln537_fu_634_p3");
    sc_trace(mVcdFile, add_ln530_fu_664_p2, "add_ln530_fu_664_p2");
    sc_trace(mVcdFile, add_ln535_fu_618_p2, "add_ln535_fu_618_p2");
    sc_trace(mVcdFile, icmp_ln498_5_fu_563_p2, "icmp_ln498_5_fu_563_p2");
    sc_trace(mVcdFile, icmp_ln498_6_fu_573_p2, "icmp_ln498_6_fu_573_p2");
    sc_trace(mVcdFile, and_ln498_3_fu_585_p2, "and_ln498_3_fu_585_p2");
    sc_trace(mVcdFile, and_ln498_fu_579_p2, "and_ln498_fu_579_p2");
    sc_trace(mVcdFile, add_ln537_fu_629_p2, "add_ln537_fu_629_p2");
    sc_trace(mVcdFile, add_ln532_fu_675_p2, "add_ln532_fu_675_p2");
    sc_trace(mVcdFile, trunc_ln508_fu_705_p1, "trunc_ln508_fu_705_p1");
    sc_trace(mVcdFile, shl_ln_fu_709_p3, "shl_ln_fu_709_p3");
    sc_trace(mVcdFile, add_ln508_fu_717_p2, "add_ln508_fu_717_p2");
    sc_trace(mVcdFile, icmp_ln1494_fu_749_p2, "icmp_ln1494_fu_749_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_1059, "ap_condition_1059");
    sc_trace(mVcdFile, ap_condition_1061, "ap_condition_1061");
    sc_trace(mVcdFile, ap_condition_161, "ap_condition_161");
    sc_trace(mVcdFile, ap_condition_272, "ap_condition_272");
#endif

    }
}

pooling2d_large_cl_nopad_pad_me::~pooling2d_large_cl_nopad_pad_me() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete layer_in_V_6_U;
    delete tmpdata_V_U;
    delete pool_V_U;
    delete grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375;
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln484_fu_510_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             !(esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())) && 
             esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_1))) {
            grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_ready.read())) {
            grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln484_fu_510_p2.read()))) {
        i0_0_reg_308 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && 
                !(esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())))) {
        i0_0_reg_308 = i0_fu_528_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, and_ln498_4_fu_591_p2.read()))) {
        i1_0_reg_319 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && 
                !(esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())))) {
        i1_0_reg_319 = i1_reg_834.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, and_ln498_4_reg_822.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln500_fu_601_p2.read()))) {
        i2_0_reg_330 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i2_0_reg_330 = i2_reg_854.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_0_reg_353 = i_reg_877.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_0_reg_353 = ap_const_lv3_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_ih_0_reg_297 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_ih_0_reg_297 = i_ih_reg_777.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_1061.read(), ap_const_boolean_1)) {
            pX_1 = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_condition_1059.read(), ap_const_boolean_1)) {
            pX_1 = add_ln535_fu_618_p2.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_272.read(), ap_const_boolean_1)) {
            pY_1 = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_condition_161.read(), ap_const_boolean_1)) {
            pY_1 = add_ln530_fu_664_p2.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_1061.read(), ap_const_boolean_1)) {
            sX_1 = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_condition_1059.read(), ap_const_boolean_1)) {
            sX_1 = select_ln537_fu_634_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_272.read(), ap_const_boolean_1)) {
            storemerge_reg_364 = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_condition_161.read(), ap_const_boolean_1)) {
            storemerge_reg_364 = select_ln532_fu_680_p3.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_V_reg_342 = pool_res_V_2_fu_755_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_V_reg_342 = pool_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done.read(), ap_const_logic_1))) {
        and_ln498_4_reg_822 = and_ln498_4_fu_591_p2.read();
        icmp_ln498_4_reg_805 = icmp_ln498_4_fu_553_p2.read();
        icmp_ln498_reg_795 = icmp_ln498_fu_543_p2.read();
        pX_1_load_reg_816 = pX_1.read();
        pY_1_load_reg_810 = pY_1.read();
        sX_1_load_reg_790 = sX_1.read();
        sY_1_load_reg_800 = sY_1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln498_4_reg_822.read()))) {
        i1_reg_834 = i1_fu_607_p2.read();
        zext_ln500_reg_826 = zext_ln500_fu_597_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i2_reg_854 = i2_fu_699_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_ih_reg_777 = i_ih_fu_516_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && !(esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln512_fu_732_p2.read()))) {
        i_reg_877 = i_fu_743_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln500_fu_601_p2.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln498_4_reg_822.read())))) {
        icmp_ln522_reg_839 = icmp_ln522_fu_613_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln522_reg_839.read()))) {
        sY_1 = storemerge_reg_364.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_add_ln508_fu_717_p2() {
    add_ln508_fu_717_p2 = (!zext_ln500_reg_826.read().is_01() || !shl_ln_fu_709_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln500_reg_826.read()) + sc_biguint<8>(shl_ln_fu_709_p3.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_add_ln530_fu_664_p2() {
    add_ln530_fu_664_p2 = (!pY_1_load_reg_810.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(pY_1_load_reg_810.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_add_ln532_fu_675_p2() {
    add_ln532_fu_675_p2 = (!sY_1_load_reg_800.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(sY_1_load_reg_800.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_add_ln535_fu_618_p2() {
    add_ln535_fu_618_p2 = (!pX_1_load_reg_816.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(pX_1_load_reg_816.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_add_ln537_fu_629_p2() {
    add_ln537_fu_629_p2 = (!sX_1_load_reg_790.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(sX_1_load_reg_790.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_and_ln498_3_fu_585_p2() {
    and_ln498_3_fu_585_p2 = (icmp_ln498_5_fu_563_p2.read() & icmp_ln498_6_fu_573_p2.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_and_ln498_4_fu_591_p2() {
    and_ln498_4_fu_591_p2 = (and_ln498_3_fu_585_p2.read() & and_ln498_fu_579_p2.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_and_ln498_fu_579_p2() {
    and_ln498_fu_579_p2 = (icmp_ln498_fu_543_p2.read() & icmp_ln498_4_fu_553_p2.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state3() {
    ap_block_state3 = (esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state3_ignore_call0() {
    ap_block_state3_ignore_call0 = (esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_block_state9() {
    ap_block_state9 = (esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_condition_1059() {
    ap_condition_1059 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln500_fu_601_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln522_fu_613_p2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, and_ln498_4_reg_822.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln522_fu_613_p2.read())));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_condition_1061() {
    ap_condition_1061 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln500_fu_601_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln522_fu_613_p2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, and_ln498_4_reg_822.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln522_fu_613_p2.read())));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_condition_161() {
    ap_condition_161 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln500_fu_601_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln522_fu_613_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln526_fu_659_p2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, and_ln498_4_reg_822.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln522_fu_613_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln526_fu_659_p2.read())));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_condition_272() {
    ap_condition_272 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln500_fu_601_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln522_fu_613_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln526_fu_659_p2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, and_ln498_4_reg_822.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln522_fu_613_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln526_fu_659_p2.read())));
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln484_fu_510_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void pooling2d_large_cl_nopad_pad_me::thread_data_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0))) {
        data_V_V_blk_n = data_V_V_empty_n.read();
    } else {
        data_V_V_blk_n = ap_const_logic_1;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_data_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())))) {
        data_V_V_read = ap_const_logic_1;
    } else {
        data_V_V_read = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start() {
    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_start_reg.read();
}

void pooling2d_large_cl_nopad_pad_me::thread_i0_fu_528_p2() {
    i0_fu_528_p2 = (!i0_0_reg_308.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i0_0_reg_308.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_i1_fu_607_p2() {
    i1_fu_607_p2 = (!i1_0_reg_319.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i1_0_reg_319.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_i2_fu_699_p2() {
    i2_fu_699_p2 = (!i2_0_reg_330.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i2_0_reg_330.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_i_fu_743_p2() {
    i_fu_743_p2 = (!i_0_reg_353.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_reg_353.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_i_ih_fu_516_p2() {
    i_ih_fu_516_p2 = (!i_ih_0_reg_297.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i_ih_0_reg_297.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln1494_fu_749_p2() {
    icmp_ln1494_fu_749_p2 = (!pool_V_q0.read().is_01() || !tmp_V_reg_342.read().is_01())? sc_lv<1>(): (sc_bigint<16>(pool_V_q0.read()) > sc_bigint<16>(tmp_V_reg_342.read()));
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln484_fu_510_p2() {
    icmp_ln484_fu_510_p2 = (!i_ih_0_reg_297.read().is_01() || !ap_const_lv8_A9.is_01())? sc_lv<1>(): sc_lv<1>(i_ih_0_reg_297.read() == ap_const_lv8_A9);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln489_fu_522_p2() {
    icmp_ln489_fu_522_p2 = (!i0_0_reg_308.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i0_0_reg_308.read() == ap_const_lv7_40);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln498_4_fu_553_p2() {
    icmp_ln498_4_fu_553_p2 = (!sY_1.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(sY_1.read() == ap_const_lv32_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln498_5_fu_563_p2() {
    icmp_ln498_5_fu_563_p2 = (!pY_1.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(pY_1.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln498_6_fu_573_p2() {
    icmp_ln498_6_fu_573_p2 = (!pX_1.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(pX_1.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln498_fu_543_p2() {
    icmp_ln498_fu_543_p2 = (!sX_1.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(sX_1.read() == ap_const_lv32_1);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln500_fu_601_p2() {
    icmp_ln500_fu_601_p2 = (!i1_0_reg_319.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_319.read() == ap_const_lv7_40);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln506_fu_693_p2() {
    icmp_ln506_fu_693_p2 = (!i2_0_reg_330.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_330.read() == ap_const_lv3_4);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln512_fu_732_p2() {
    icmp_ln512_fu_732_p2 = (!i_0_reg_353.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_353.read() == ap_const_lv3_4);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln522_fu_613_p2() {
    icmp_ln522_fu_613_p2 = (!pX_1_load_reg_816.read().is_01() || !ap_const_lv32_C.is_01())? sc_lv<1>(): sc_lv<1>(pX_1_load_reg_816.read() == ap_const_lv32_C);
}

void pooling2d_large_cl_nopad_pad_me::thread_icmp_ln526_fu_659_p2() {
    icmp_ln526_fu_659_p2 = (!pY_1_load_reg_810.read().is_01() || !ap_const_lv32_C.is_01())? sc_lv<1>(): sc_lv<1>(pY_1_load_reg_810.read() == ap_const_lv32_C);
}

void pooling2d_large_cl_nopad_pad_me::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln484_fu_510_p2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_layer_in_V_6_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        layer_in_V_6_address0 =  (sc_lv<8>) (zext_ln508_2_fu_722_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_V_6_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_address0.read();
    } else {
        layer_in_V_6_address0 = "XXXXXXXX";
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_layer_in_V_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        layer_in_V_6_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_V_6_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_ce0.read();
    } else {
        layer_in_V_6_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_layer_in_V_6_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_V_6_we0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_output_V_we0.read();
    } else {
        layer_in_V_6_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_pool_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        pool_V_address0 =  (sc_lv<2>) (zext_ln513_fu_738_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        pool_V_address0 =  (sc_lv<2>) (zext_ln508_fu_727_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        pool_V_address0 =  (sc_lv<2>) (ap_const_lv64_0);
    } else {
        pool_V_address0 =  (sc_lv<2>) ("XX");
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_pool_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          !(esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        pool_V_ce0 = ap_const_logic_1;
    } else {
        pool_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_pool_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        pool_V_we0 = ap_const_logic_1;
    } else {
        pool_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_pool_res_V_2_fu_755_p3() {
    pool_res_V_2_fu_755_p3 = (!icmp_ln1494_fu_749_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_fu_749_p2.read()[0].to_bool())? pool_V_q0.read(): tmp_V_reg_342.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_res_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1))) {
        res_V_V_blk_n = res_V_V_full_n.read();
    } else {
        res_V_V_blk_n = ap_const_logic_1;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_res_V_V_din() {
    res_V_V_din = tmp_V_reg_342.read();
}

void pooling2d_large_cl_nopad_pad_me::thread_res_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())))) {
        res_V_V_write = ap_const_logic_1;
    } else {
        res_V_V_write = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_select_ln532_fu_680_p3() {
    select_ln532_fu_680_p3 = (!icmp_ln498_4_reg_805.read()[0].is_01())? sc_lv<32>(): ((icmp_ln498_4_reg_805.read()[0].to_bool())? ap_const_lv32_0: add_ln532_fu_675_p2.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_select_ln537_fu_634_p3() {
    select_ln537_fu_634_p3 = (!icmp_ln498_reg_795.read()[0].is_01())? sc_lv<32>(): ((icmp_ln498_reg_795.read()[0].to_bool())? ap_const_lv32_0: add_ln537_fu_629_p2.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_shl_ln_fu_709_p3() {
    shl_ln_fu_709_p3 = esl_concat<2,6>(trunc_ln508_fu_705_p1.read(), ap_const_lv6_0);
}

void pooling2d_large_cl_nopad_pad_me::thread_start_out() {
    start_out = real_start.read();
}

void pooling2d_large_cl_nopad_pad_me::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_tmpdata_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0))) {
        tmpdata_V_address0 =  (sc_lv<6>) (zext_ln492_fu_534_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmpdata_V_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_address0.read();
    } else {
        tmpdata_V_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_tmpdata_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())))) {
        tmpdata_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmpdata_V_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_data_V_ce0.read();
    } else {
        tmpdata_V_ce0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_tmpdata_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())))) {
        tmpdata_V_we0 = ap_const_logic_1;
    } else {
        tmpdata_V_we0 = ap_const_logic_0;
    }
}

void pooling2d_large_cl_nopad_pad_me::thread_trunc_ln508_fu_705_p1() {
    trunc_ln508_fu_705_p1 = i2_0_reg_330.read().range(2-1, 0);
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln492_fu_534_p1() {
    zext_ln492_fu_534_p1 = esl_zext<64,7>(i0_0_reg_308.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln500_fu_597_p1() {
    zext_ln500_fu_597_p1 = esl_zext<8,7>(i1_0_reg_319.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln508_2_fu_722_p1() {
    zext_ln508_2_fu_722_p1 = esl_zext<64,8>(add_ln508_fu_717_p2.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln508_fu_727_p1() {
    zext_ln508_fu_727_p1 = esl_zext<64,3>(i2_0_reg_330.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_zext_ln513_fu_738_p1() {
    zext_ln513_fu_738_p1 = esl_zext<64,3>(i_0_reg_353.read());
}

void pooling2d_large_cl_nopad_pad_me::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln484_fu_510_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read())) && esl_seteq<1,1,1>(icmp_ln489_fu_522_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config15_s_fu_375_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln500_fu_601_p2.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln498_4_reg_822.read())))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln506_fu_693_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && !(esl_seteq<1,1,1>(icmp_ln512_fu_732_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_V_full_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln512_fu_732_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

