// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcku115-flvb2104-2-i,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.375000,HLS_SYN_LAT=1204219,HLS_SYN_TPT=1138690,HLS_SYN_MEM=77,HLS_SYN_DSP=197,HLS_SYN_FF=15469,HLS_SYN_LUT=25598,HLS_VERSION=2019_2}" *)

module myproject (
        conv2d_input_V_V_TDATA,
        layer19_out_V_V_TDATA,
        const_size_in_1,
        const_size_out_1,
        ap_clk,
        ap_rst_n,
        const_size_in_1_ap_vld,
        const_size_out_1_ap_vld,
        ap_start,
        ap_done,
        conv2d_input_V_V_TVALID,
        conv2d_input_V_V_TREADY,
        layer19_out_V_V_TVALID,
        layer19_out_V_V_TREADY,
        ap_ready,
        ap_idle
);


input  [15:0] conv2d_input_V_V_TDATA;
output  [15:0] layer19_out_V_V_TDATA;
output  [15:0] const_size_in_1;
output  [15:0] const_size_out_1;
input   ap_clk;
input   ap_rst_n;
output   const_size_in_1_ap_vld;
output   const_size_out_1_ap_vld;
input   ap_start;
output   ap_done;
input   conv2d_input_V_V_TVALID;
output   conv2d_input_V_V_TREADY;
output   layer19_out_V_V_TVALID;
input   layer19_out_V_V_TREADY;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire   [15:0] Block_proc_U0_const_size_in_1;
wire    Block_proc_U0_const_size_in_1_ap_vld;
wire   [15:0] Block_proc_U0_const_size_out_1;
wire    Block_proc_U0_const_size_out_1_ap_vld;
wire    ap_sync_continue;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_start;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_done;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_continue;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_idle;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_start_out;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_start_write;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_data_V_V_TREADY;
wire   [15:0] zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_res_V_V_din;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_res_V_V_write;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_start;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_done;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_continue;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_idle;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_ready;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_start_out;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_start_write;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_data_V_V_read;
wire   [15:0] conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_res_V_V_din;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_res_V_V_write;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_start;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_done;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_continue;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_idle;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_ready;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_start_out;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_start_write;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_data_V_V_read;
wire   [15:0] relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_res_V_V_din;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_res_V_V_write;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_start;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_done;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_continue;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_idle;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_ready;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_start_out;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_start_write;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_data_V_V_read;
wire   [15:0] conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_res_V_V_din;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_res_V_V_write;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_start;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_done;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_continue;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_idle;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_ready;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_start_out;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_start_write;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_data_V_V_read;
wire   [15:0] relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_res_V_V_din;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_res_V_V_write;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_start;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_done;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_continue;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_idle;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_ready;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_start_out;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_start_write;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_data_V_V_read;
wire   [15:0] pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_res_V_V_din;
wire    pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_res_V_V_write;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_start;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_done;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_continue;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_idle;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_ready;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_start_out;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_start_write;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_data_V_V_read;
wire   [15:0] zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_res_V_V_din;
wire    zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_res_V_V_write;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_start;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_done;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_continue;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_idle;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_ready;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_start_out;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_start_write;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_data_V_V_read;
wire   [15:0] conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_res_V_V_din;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_res_V_V_write;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_start;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_done;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_continue;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_idle;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_ready;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_start_out;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_start_write;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_data_V_V_read;
wire   [15:0] relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_res_V_V_din;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_res_V_V_write;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_start;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_done;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_continue;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_idle;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_ready;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_start_out;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_start_write;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_data_V_V_read;
wire   [15:0] conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_res_V_V_din;
wire    conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_res_V_V_write;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_start;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_done;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_continue;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_idle;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_ready;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_start_out;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_start_write;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_data_V_V_read;
wire   [15:0] relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_res_V_V_din;
wire    relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_res_V_V_write;
wire    pooling2d_large_cl_nopad_pad_me_U0_ap_start;
wire    pooling2d_large_cl_nopad_pad_me_U0_ap_done;
wire    pooling2d_large_cl_nopad_pad_me_U0_ap_continue;
wire    pooling2d_large_cl_nopad_pad_me_U0_ap_idle;
wire    pooling2d_large_cl_nopad_pad_me_U0_ap_ready;
wire    pooling2d_large_cl_nopad_pad_me_U0_start_out;
wire    pooling2d_large_cl_nopad_pad_me_U0_start_write;
wire    pooling2d_large_cl_nopad_pad_me_U0_data_V_V_read;
wire   [15:0] pooling2d_large_cl_nopad_pad_me_U0_res_V_V_din;
wire    pooling2d_large_cl_nopad_pad_me_U0_res_V_V_write;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_start;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_done;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_continue;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_idle;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_ready;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_start_out;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_start_write;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_data_V_V_read;
wire   [15:0] dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_res_V_V_din;
wire    dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_res_V_V_write;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_start;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_done;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_continue;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_idle;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_ready;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_data_V_V_read;
wire   [15:0] sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_res_V_V_TDATA;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_res_V_V_TVALID;
wire    layer20_out_V_V_full_n;
wire   [15:0] layer20_out_V_V_dout;
wire    layer20_out_V_V_empty_n;
wire    layer2_out_V_V_full_n;
wire   [15:0] layer2_out_V_V_dout;
wire    layer2_out_V_V_empty_n;
wire    layer4_out_V_V_full_n;
wire   [15:0] layer4_out_V_V_dout;
wire    layer4_out_V_V_empty_n;
wire    layer5_out_V_V_full_n;
wire   [15:0] layer5_out_V_V_dout;
wire    layer5_out_V_V_empty_n;
wire    layer7_out_V_V_full_n;
wire   [15:0] layer7_out_V_V_dout;
wire    layer7_out_V_V_empty_n;
wire    layer8_out_V_V_full_n;
wire   [15:0] layer8_out_V_V_dout;
wire    layer8_out_V_V_empty_n;
wire    layer21_out_V_V_full_n;
wire   [15:0] layer21_out_V_V_dout;
wire    layer21_out_V_V_empty_n;
wire    layer9_out_V_V_full_n;
wire   [15:0] layer9_out_V_V_dout;
wire    layer9_out_V_V_empty_n;
wire    layer11_out_V_V_full_n;
wire   [15:0] layer11_out_V_V_dout;
wire    layer11_out_V_V_empty_n;
wire    layer12_out_V_V_full_n;
wire   [15:0] layer12_out_V_V_dout;
wire    layer12_out_V_V_empty_n;
wire    layer14_out_V_V_full_n;
wire   [15:0] layer14_out_V_V_dout;
wire    layer14_out_V_V_empty_n;
wire    layer15_out_V_V_full_n;
wire   [15:0] layer15_out_V_V_dout;
wire    layer15_out_V_V_empty_n;
wire    layer17_out_V_V_full_n;
wire   [15:0] layer17_out_V_V_dout;
wire    layer17_out_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_proc_U0_ap_ready;
wire    ap_sync_Block_proc_U0_ap_ready;
reg   [1:0] Block_proc_U0_ap_ready_count;
reg    ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready;
wire    ap_sync_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready;
reg   [1:0] zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready_count;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;
wire   [0:0] start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_din;
wire    start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_dout;
wire    start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_empty_n;
wire   [0:0] start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_din;
wire    start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_full_n;
wire   [0:0] start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_dout;
wire    start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_din;
wire    start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_dout;
wire    start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_empty_n;
wire   [0:0] start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_din;
wire    start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_full_n;
wire   [0:0] start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_dout;
wire    start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_empty_n;
wire   [0:0] start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_din;
wire    start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_full_n;
wire   [0:0] start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_dout;
wire    start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_empty_n;
wire   [0:0] start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_din;
wire    start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_full_n;
wire   [0:0] start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_dout;
wire    start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_din;
wire    start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_dout;
wire    start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_empty_n;
wire   [0:0] start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_din;
wire    start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_full_n;
wire   [0:0] start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_dout;
wire    start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_din;
wire    start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_dout;
wire    start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_empty_n;
wire   [0:0] start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_din;
wire    start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_full_n;
wire   [0:0] start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_dout;
wire    start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_empty_n;
wire   [0:0] start_for_pooling2d_large_cl_nopad_pad_me_U0_din;
wire    start_for_pooling2d_large_cl_nopad_pad_me_U0_full_n;
wire   [0:0] start_for_pooling2d_large_cl_nopad_pad_me_U0_dout;
wire    start_for_pooling2d_large_cl_nopad_pad_me_U0_empty_n;
wire   [0:0] start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_din;
wire    start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_full_n;
wire   [0:0] start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_dout;
wire    start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_empty_n;
wire   [0:0] start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_din;
wire    start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_full_n;
wire   [0:0] start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_dout;
wire    start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_empty_n;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_start_full_n;
wire    sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_proc_U0_ap_ready = 1'b0;
#0 Block_proc_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready = 1'b0;
#0 zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready_count = 2'd0;
end

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .const_size_in_1(Block_proc_U0_const_size_in_1),
    .const_size_in_1_ap_vld(Block_proc_U0_const_size_in_1_ap_vld),
    .const_size_out_1(Block_proc_U0_const_size_out_1),
    .const_size_out_1_ap_vld(Block_proc_U0_const_size_out_1_ap_vld)
);

zeropad2d_cl_me_ap_fixed_ap_fixed_config20_s zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_full_n),
    .ap_done(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_done),
    .ap_continue(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_continue),
    .ap_idle(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_idle),
    .ap_ready(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready),
    .start_out(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_start_out),
    .start_write(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_start_write),
    .data_V_V_TDATA(conv2d_input_V_V_TDATA),
    .data_V_V_TVALID(conv2d_input_V_V_TVALID),
    .data_V_V_TREADY(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_data_V_V_TREADY),
    .res_V_V_din(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_res_V_V_din),
    .res_V_V_full_n(layer20_out_V_V_full_n),
    .res_V_V_write(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_res_V_V_write)
);

conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_s conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_start),
    .start_full_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_full_n),
    .ap_done(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_ready),
    .start_out(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_start_out),
    .start_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_start_write),
    .data_V_V_dout(layer20_out_V_V_dout),
    .data_V_V_empty_n(layer20_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_res_V_V_din),
    .res_V_V_full_n(layer2_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_res_V_V_write)
);

relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_s relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_full_n),
    .ap_done(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_done),
    .ap_continue(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_continue),
    .ap_idle(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_idle),
    .ap_ready(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_ready),
    .start_out(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_start_out),
    .start_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_start_write),
    .data_V_V_dout(layer2_out_V_V_dout),
    .data_V_V_empty_n(layer2_out_V_V_empty_n),
    .data_V_V_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_data_V_V_read),
    .res_V_V_din(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_res_V_V_din),
    .res_V_V_full_n(layer4_out_V_V_full_n),
    .res_V_V_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_res_V_V_write)
);

conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_s conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_start),
    .start_full_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_full_n),
    .ap_done(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_done),
    .ap_continue(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_continue),
    .ap_idle(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_idle),
    .ap_ready(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_ready),
    .start_out(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_start_out),
    .start_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_start_write),
    .data_V_V_dout(layer4_out_V_V_dout),
    .data_V_V_empty_n(layer4_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_res_V_V_din),
    .res_V_V_full_n(layer5_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_res_V_V_write)
);

relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_s relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_start),
    .start_full_n(start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_full_n),
    .ap_done(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_done),
    .ap_continue(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_continue),
    .ap_idle(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_idle),
    .ap_ready(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_ready),
    .start_out(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_start_out),
    .start_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_start_write),
    .data_V_V_dout(layer5_out_V_V_dout),
    .data_V_V_empty_n(layer5_out_V_V_empty_n),
    .data_V_V_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_data_V_V_read),
    .res_V_V_din(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_res_V_V_din),
    .res_V_V_full_n(layer7_out_V_V_full_n),
    .res_V_V_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_res_V_V_write)
);

pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_s pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_start),
    .start_full_n(start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_full_n),
    .ap_done(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_done),
    .ap_continue(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_continue),
    .ap_idle(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_idle),
    .ap_ready(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_ready),
    .start_out(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_start_out),
    .start_write(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_start_write),
    .data_V_V_dout(layer7_out_V_V_dout),
    .data_V_V_empty_n(layer7_out_V_V_empty_n),
    .data_V_V_read(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_data_V_V_read),
    .res_V_V_din(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_res_V_V_din),
    .res_V_V_full_n(layer8_out_V_V_full_n),
    .res_V_V_write(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_res_V_V_write)
);

zeropad2d_cl_me_ap_fixed_ap_fixed_config21_s zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_full_n),
    .ap_done(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_done),
    .ap_continue(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_continue),
    .ap_idle(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_idle),
    .ap_ready(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_ready),
    .start_out(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_start_out),
    .start_write(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_start_write),
    .data_V_V_dout(layer8_out_V_V_dout),
    .data_V_V_empty_n(layer8_out_V_V_empty_n),
    .data_V_V_read(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_data_V_V_read),
    .res_V_V_din(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_res_V_V_din),
    .res_V_V_full_n(layer21_out_V_V_full_n),
    .res_V_V_write(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_res_V_V_write)
);

conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_s conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_start),
    .start_full_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_full_n),
    .ap_done(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_done),
    .ap_continue(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_continue),
    .ap_idle(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_idle),
    .ap_ready(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_ready),
    .start_out(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_start_out),
    .start_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_start_write),
    .data_V_V_dout(layer21_out_V_V_dout),
    .data_V_V_empty_n(layer21_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_res_V_V_din),
    .res_V_V_full_n(layer9_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_res_V_V_write)
);

relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_s relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_full_n),
    .ap_done(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_done),
    .ap_continue(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_continue),
    .ap_idle(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_idle),
    .ap_ready(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_ready),
    .start_out(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_start_out),
    .start_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_start_write),
    .data_V_V_dout(layer9_out_V_V_dout),
    .data_V_V_empty_n(layer9_out_V_V_empty_n),
    .data_V_V_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_data_V_V_read),
    .res_V_V_din(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_res_V_V_din),
    .res_V_V_full_n(layer11_out_V_V_full_n),
    .res_V_V_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_res_V_V_write)
);

conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_s conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_start),
    .start_full_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_full_n),
    .ap_done(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_done),
    .ap_continue(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_continue),
    .ap_idle(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_idle),
    .ap_ready(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_ready),
    .start_out(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_start_out),
    .start_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_start_write),
    .data_V_V_dout(layer11_out_V_V_dout),
    .data_V_V_empty_n(layer11_out_V_V_empty_n),
    .data_V_V_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_data_V_V_read),
    .res_V_V_din(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_res_V_V_din),
    .res_V_V_full_n(layer12_out_V_V_full_n),
    .res_V_V_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_res_V_V_write)
);

relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_s relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_start),
    .start_full_n(start_for_pooling2d_large_cl_nopad_pad_me_U0_full_n),
    .ap_done(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_done),
    .ap_continue(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_continue),
    .ap_idle(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_idle),
    .ap_ready(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_ready),
    .start_out(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_start_out),
    .start_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_start_write),
    .data_V_V_dout(layer12_out_V_V_dout),
    .data_V_V_empty_n(layer12_out_V_V_empty_n),
    .data_V_V_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_data_V_V_read),
    .res_V_V_din(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_res_V_V_din),
    .res_V_V_full_n(layer14_out_V_V_full_n),
    .res_V_V_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_res_V_V_write)
);

pooling2d_large_cl_nopad_pad_me pooling2d_large_cl_nopad_pad_me_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_large_cl_nopad_pad_me_U0_ap_start),
    .start_full_n(start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_full_n),
    .ap_done(pooling2d_large_cl_nopad_pad_me_U0_ap_done),
    .ap_continue(pooling2d_large_cl_nopad_pad_me_U0_ap_continue),
    .ap_idle(pooling2d_large_cl_nopad_pad_me_U0_ap_idle),
    .ap_ready(pooling2d_large_cl_nopad_pad_me_U0_ap_ready),
    .start_out(pooling2d_large_cl_nopad_pad_me_U0_start_out),
    .start_write(pooling2d_large_cl_nopad_pad_me_U0_start_write),
    .data_V_V_dout(layer14_out_V_V_dout),
    .data_V_V_empty_n(layer14_out_V_V_empty_n),
    .data_V_V_read(pooling2d_large_cl_nopad_pad_me_U0_data_V_V_read),
    .res_V_V_din(pooling2d_large_cl_nopad_pad_me_U0_res_V_V_din),
    .res_V_V_full_n(layer15_out_V_V_full_n),
    .res_V_V_write(pooling2d_large_cl_nopad_pad_me_U0_res_V_V_write)
);

dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_start),
    .start_full_n(start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_full_n),
    .ap_done(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_done),
    .ap_continue(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_continue),
    .ap_idle(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_idle),
    .ap_ready(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_ready),
    .start_out(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_start_out),
    .start_write(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_start_write),
    .data_V_V_dout(layer15_out_V_V_dout),
    .data_V_V_empty_n(layer15_out_V_V_empty_n),
    .data_V_V_read(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_data_V_V_read),
    .res_V_V_din(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_res_V_V_din),
    .res_V_V_full_n(layer17_out_V_V_full_n),
    .res_V_V_write(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_res_V_V_write)
);

sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_s sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_start),
    .ap_done(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_done),
    .ap_continue(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_continue),
    .ap_idle(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_idle),
    .ap_ready(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_ready),
    .data_V_V_dout(layer17_out_V_V_dout),
    .data_V_V_empty_n(layer17_out_V_V_empty_n),
    .data_V_V_read(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_data_V_V_read),
    .res_V_V_TDATA(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_res_V_V_TDATA),
    .res_V_V_TVALID(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_res_V_V_TVALID),
    .res_V_V_TREADY(layer19_out_V_V_TREADY)
);

fifo_w16_d1_A layer20_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_res_V_V_din),
    .if_full_n(layer20_out_V_V_full_n),
    .if_write(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_res_V_V_write),
    .if_dout(layer20_out_V_V_dout),
    .if_empty_n(layer20_out_V_V_empty_n),
    .if_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_data_V_V_read)
);

fifo_w16_d1_A layer2_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_res_V_V_din),
    .if_full_n(layer2_out_V_V_full_n),
    .if_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_res_V_V_write),
    .if_dout(layer2_out_V_V_dout),
    .if_empty_n(layer2_out_V_V_empty_n),
    .if_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_data_V_V_read)
);

fifo_w16_d1_A layer4_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_res_V_V_din),
    .if_full_n(layer4_out_V_V_full_n),
    .if_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_res_V_V_write),
    .if_dout(layer4_out_V_V_dout),
    .if_empty_n(layer4_out_V_V_empty_n),
    .if_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_data_V_V_read)
);

fifo_w16_d1_A layer5_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_res_V_V_din),
    .if_full_n(layer5_out_V_V_full_n),
    .if_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_res_V_V_write),
    .if_dout(layer5_out_V_V_dout),
    .if_empty_n(layer5_out_V_V_empty_n),
    .if_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_data_V_V_read)
);

fifo_w16_d1_A layer7_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_res_V_V_din),
    .if_full_n(layer7_out_V_V_full_n),
    .if_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_res_V_V_write),
    .if_dout(layer7_out_V_V_dout),
    .if_empty_n(layer7_out_V_V_empty_n),
    .if_read(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_data_V_V_read)
);

fifo_w16_d1_A layer8_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_res_V_V_din),
    .if_full_n(layer8_out_V_V_full_n),
    .if_write(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_res_V_V_write),
    .if_dout(layer8_out_V_V_dout),
    .if_empty_n(layer8_out_V_V_empty_n),
    .if_read(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_data_V_V_read)
);

fifo_w16_d1_A layer21_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_res_V_V_din),
    .if_full_n(layer21_out_V_V_full_n),
    .if_write(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_res_V_V_write),
    .if_dout(layer21_out_V_V_dout),
    .if_empty_n(layer21_out_V_V_empty_n),
    .if_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_data_V_V_read)
);

fifo_w16_d1_A layer9_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_res_V_V_din),
    .if_full_n(layer9_out_V_V_full_n),
    .if_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_res_V_V_write),
    .if_dout(layer9_out_V_V_dout),
    .if_empty_n(layer9_out_V_V_empty_n),
    .if_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_data_V_V_read)
);

fifo_w16_d1_A layer11_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_res_V_V_din),
    .if_full_n(layer11_out_V_V_full_n),
    .if_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_res_V_V_write),
    .if_dout(layer11_out_V_V_dout),
    .if_empty_n(layer11_out_V_V_empty_n),
    .if_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_data_V_V_read)
);

fifo_w16_d1_A layer12_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_res_V_V_din),
    .if_full_n(layer12_out_V_V_full_n),
    .if_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_res_V_V_write),
    .if_dout(layer12_out_V_V_dout),
    .if_empty_n(layer12_out_V_V_empty_n),
    .if_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_data_V_V_read)
);

fifo_w16_d1_A layer14_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_res_V_V_din),
    .if_full_n(layer14_out_V_V_full_n),
    .if_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_res_V_V_write),
    .if_dout(layer14_out_V_V_dout),
    .if_empty_n(layer14_out_V_V_empty_n),
    .if_read(pooling2d_large_cl_nopad_pad_me_U0_data_V_V_read)
);

fifo_w16_d1_A layer15_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_large_cl_nopad_pad_me_U0_res_V_V_din),
    .if_full_n(layer15_out_V_V_full_n),
    .if_write(pooling2d_large_cl_nopad_pad_me_U0_res_V_V_write),
    .if_dout(layer15_out_V_V_dout),
    .if_empty_n(layer15_out_V_V_empty_n),
    .if_read(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_data_V_V_read)
);

fifo_w16_d1_A layer17_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_res_V_V_din),
    .if_full_n(layer17_out_V_V_full_n),
    .if_write(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_res_V_V_write),
    .if_dout(layer17_out_V_V_dout),
    .if_empty_n(layer17_out_V_V_empty_n),
    .if_read(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_data_V_V_read)
);

start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_confgj9 start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_confgj9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_din),
    .if_full_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_full_n),
    .if_write(zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_start_write),
    .if_dout(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_empty_n),
    .if_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_ready)
);

start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_configk9 start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_configk9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_din),
    .if_full_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_full_n),
    .if_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_start_write),
    .if_dout(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_dout),
    .if_empty_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_empty_n),
    .if_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_ready)
);

start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_confgl9 start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_confgl9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_din),
    .if_full_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_full_n),
    .if_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_start_write),
    .if_dout(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_empty_n),
    .if_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_ready)
);

start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_configm9 start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_configm9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_din),
    .if_full_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_full_n),
    .if_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_start_write),
    .if_dout(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_dout),
    .if_empty_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_empty_n),
    .if_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_ready)
);

start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixgnb start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixgnb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_din),
    .if_full_n(start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_full_n),
    .if_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_start_write),
    .if_dout(start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_dout),
    .if_empty_n(start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_empty_n),
    .if_read(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_ready)
);

start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0 start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_din),
    .if_full_n(start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_full_n),
    .if_write(pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_start_write),
    .if_dout(start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_dout),
    .if_empty_n(start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_empty_n),
    .if_read(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_ready)
);

start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_confgob start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_confgob_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_din),
    .if_full_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_full_n),
    .if_write(zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_start_write),
    .if_dout(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_empty_n),
    .if_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_ready)
);

start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_configpb start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_configpb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_din),
    .if_full_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_full_n),
    .if_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_start_write),
    .if_dout(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_dout),
    .if_empty_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_empty_n),
    .if_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_ready)
);

start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_confgqb start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_confgqb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_din),
    .if_full_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_full_n),
    .if_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_start_write),
    .if_dout(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_empty_n),
    .if_read(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_ready)
);

start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_configrb start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_configrb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_din),
    .if_full_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_full_n),
    .if_write(conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_start_write),
    .if_dout(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_dout),
    .if_empty_n(start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_empty_n),
    .if_read(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_ready)
);

start_for_pooling2d_large_cl_nopad_pad_me_U0 start_for_pooling2d_large_cl_nopad_pad_me_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_large_cl_nopad_pad_me_U0_din),
    .if_full_n(start_for_pooling2d_large_cl_nopad_pad_me_U0_full_n),
    .if_write(relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_start_write),
    .if_dout(start_for_pooling2d_large_cl_nopad_pad_me_U0_dout),
    .if_empty_n(start_for_pooling2d_large_cl_nopad_pad_me_U0_empty_n),
    .if_read(pooling2d_large_cl_nopad_pad_me_U0_ap_ready)
);

start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0 start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_din),
    .if_full_n(start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_full_n),
    .if_write(pooling2d_large_cl_nopad_pad_me_U0_start_write),
    .if_dout(start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_dout),
    .if_empty_n(start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_empty_n),
    .if_read(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_ready)
);

start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0 start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_din),
    .if_full_n(start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_full_n),
    .if_write(dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_start_write),
    .if_dout(start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_dout),
    .if_empty_n(start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_empty_n),
    .if_read(sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_proc_U0_ap_ready <= ap_sync_Block_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready <= ap_sync_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == Block_proc_U0_ap_ready))) begin
        Block_proc_U0_ap_ready_count <= (Block_proc_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == Block_proc_U0_ap_ready))) begin
        Block_proc_U0_ap_ready_count <= (Block_proc_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready_count <= (zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready == 1'b1))) begin
        zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready_count <= (zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready_count + 2'd1);
    end
end

assign Block_proc_U0_ap_continue = ap_sync_done;

assign Block_proc_U0_ap_start = ((ap_sync_reg_Block_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_proc_U0_start_full_n = 1'b1;

assign Block_proc_U0_start_write = 1'b0;

assign ap_done = ap_sync_done;

assign ap_idle = (zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_idle & zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_idle & sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_idle & relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_idle & relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_idle & relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_idle & relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_idle & pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_idle & pooling2d_large_cl_nopad_pad_me_U0_ap_idle & dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_idle & conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_idle & conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_idle & conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_idle & conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_idle & Block_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_proc_U0_ap_ready = (ap_sync_reg_Block_proc_U0_ap_ready | Block_proc_U0_ap_ready);

assign ap_sync_continue = ap_sync_done;

assign ap_sync_done = (sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_done & Block_proc_U0_ap_done);

assign ap_sync_ready = (ap_sync_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready & ap_sync_Block_proc_U0_ap_ready);

assign ap_sync_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready = (zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready | ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready);

assign const_size_in_1 = Block_proc_U0_const_size_in_1;

assign const_size_in_1_ap_vld = Block_proc_U0_const_size_in_1_ap_vld;

assign const_size_out_1 = Block_proc_U0_const_size_out_1;

assign const_size_out_1_ap_vld = Block_proc_U0_const_size_out_1_ap_vld;

assign conv2d_input_V_V_TREADY = zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_data_V_V_TREADY;

assign conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_continue = 1'b1;

assign conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_ap_start = start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_empty_n;

assign conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_ap_start = start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_empty_n;

assign conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_continue = 1'b1;

assign conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_ap_start = start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_empty_n;

assign conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_continue = 1'b1;

assign conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_ap_start = start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_empty_n;

assign dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_continue = 1'b1;

assign dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_ap_start = start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_empty_n;

assign layer19_out_V_V_TDATA = sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_res_V_V_TDATA;

assign layer19_out_V_V_TVALID = sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_res_V_V_TVALID;

assign pooling2d_large_cl_nopad_pad_me_U0_ap_continue = 1'b1;

assign pooling2d_large_cl_nopad_pad_me_U0_ap_start = start_for_pooling2d_large_cl_nopad_pad_me_U0_empty_n;

assign pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_continue = 1'b1;

assign pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_ap_start = start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_empty_n;

assign relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_continue = 1'b1;

assign relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_ap_start = start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_empty_n;

assign relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_continue = 1'b1;

assign relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_ap_start = start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_empty_n;

assign relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_continue = 1'b1;

assign relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_ap_start = start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_empty_n;

assign relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_continue = 1'b1;

assign relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_ap_start = start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_empty_n;

assign sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_continue = ap_sync_done;

assign sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_ap_start = start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_empty_n;

assign sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_start_full_n = 1'b1;

assign sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_start_write = 1'b0;

assign start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config12_U0_din = 1'b1;

assign start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_U0_din = 1'b1;

assign start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config5_U0_din = 1'b1;

assign start_for_conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config9_U0_din = 1'b1;

assign start_for_dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_U0_din = 1'b1;

assign start_for_pooling2d_large_cl_nopad_pad_me_U0_din = 1'b1;

assign start_for_pooling2d_large_cl_nopad_pad_me_ap_fixed_ap_fixed_config8_U0_din = 1'b1;

assign start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config11_U0_din = 1'b1;

assign start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config14_U0_din = 1'b1;

assign start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config4_U0_din = 1'b1;

assign start_for_relu_me_ap_fixed_ap_fixed_16_4_5_3_0_relu_config7_U0_din = 1'b1;

assign start_for_sigmoid_me_ap_fixed_ap_fixed_sigmoid_config19_U0_din = 1'b1;

assign start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_din = 1'b1;

assign zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_continue = 1'b1;

assign zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_start = ((ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config20_U0_ap_ready ^ 1'b1) & ap_start);

assign zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_continue = 1'b1;

assign zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_ap_start = start_for_zeropad2d_cl_me_ap_fixed_ap_fixed_config21_U0_empty_n;

endmodule //myproject
